# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt5_match.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1269, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saveGoodMatchButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveGoodMatchButton.setGeometry(QtCore.QRect(430, 60, 75, 23))
        self.saveGoodMatchButton.setObjectName("saveGoodMatchButton")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(340, 140, 75, 23))
        self.nextButton.setObjectName("nextButton")
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setGeometry(QtCore.QRect(260, 140, 75, 23))
        self.prevButton.setObjectName("prevButton")
        self.filenameLabel = QtWidgets.QLabel(self.centralwidget)
        self.filenameLabel.setGeometry(QtCore.QRect(150, 10, 241, 21))
        self.filenameLabel.setObjectName("filenameLabel")
        self.templateDateLabel = QtWidgets.QLabel(self.centralwidget)
        self.templateDateLabel.setGeometry(QtCore.QRect(60, 80, 121, 16))
        self.templateDateLabel.setObjectName("templateDateLabel")
        self.matchDateLabel = QtWidgets.QLabel(self.centralwidget)
        self.matchDateLabel.setGeometry(QtCore.QRect(280, 80, 131, 16))
        self.matchDateLabel.setObjectName("matchDateLabel")
        self.saveExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveExitButton.setGeometry(QtCore.QRect(300, 170, 75, 23))
        self.saveExitButton.setObjectName("saveExitButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 60, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(530, 10, 721, 751))
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setObjectName("image")
        self.saveMaybeMatchButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveMaybeMatchButton.setGeometry(QtCore.QRect(430, 90, 75, 23))
        self.saveMaybeMatchButton.setObjectName("saveMaybeMatchButton")
        self.saveNotGoodMatchButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveNotGoodMatchButton.setGeometry(QtCore.QRect(430, 120, 75, 23))
        self.saveNotGoodMatchButton.setObjectName("saveNotGoodMatchButton")
        self.saveNoMatchButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveNoMatchButton.setGeometry(QtCore.QRect(430, 150, 75, 23))
        self.saveNoMatchButton.setObjectName("saveNoMatchButton")
        self.locationValue = QtWidgets.QLabel(self.centralwidget)
        self.locationValue.setGeometry(QtCore.QRect(60, 100, 181, 20))
        self.locationValue.setObjectName("locationValue")
        self.inCatalogValue = QtWidgets.QLabel(self.centralwidget)
        self.inCatalogValue.setGeometry(QtCore.QRect(280, 110, 91, 16))
        self.inCatalogValue.setObjectName("inCatalogValue")
        self.mapWidget = QtWidgets.QFrame(self.centralwidget)
        self.mapWidget.setGeometry(QtCore.QRect(30, 320, 471, 441))
        self.mapWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.mapWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mapWidget.setObjectName("mapWidget")
        self.mapInset = QtWidgets.QFrame(self.mapWidget)
        self.mapInset.setGeometry(QtCore.QRect(259, 279, 201, 151))
        self.mapInset.setFrameShape(QtWidgets.QFrame.Panel)
        self.mapInset.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mapInset.setLineWidth(2)
        self.mapInset.setObjectName("mapInset")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 61, 16))
        self.label_3.setObjectName("label_3")
        self.magnitudeValue = QtWidgets.QLabel(self.centralwidget)
        self.magnitudeValue.setGeometry(QtCore.QRect(140, 130, 47, 13))
        self.magnitudeValue.setObjectName("magnitudeValue")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1269, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveGoodMatchButton.setText(_translate("MainWindow", "Good Match"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.prevButton.setText(_translate("MainWindow", "Prev"))
        self.filenameLabel.setText(_translate("MainWindow", "filename"))
        self.templateDateLabel.setText(_translate("MainWindow", "Template Date"))
        self.matchDateLabel.setText(_translate("MainWindow", "Match Date"))
        self.saveExitButton.setText(_translate("MainWindow", "Save / Exit"))
        self.label.setText(_translate("MainWindow", "Template"))
        self.label_2.setText(_translate("MainWindow", "Match"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.saveMaybeMatchButton.setText(_translate("MainWindow", "Maybe Match"))
        self.saveNotGoodMatchButton.setText(_translate("MainWindow", "Not Good"))
        self.saveNoMatchButton.setText(_translate("MainWindow", "No Match"))
        self.locationValue.setText(_translate("MainWindow", "Location"))
        self.inCatalogValue.setText(_translate("MainWindow", "In Catalog"))
        self.label_3.setText(_translate("MainWindow", "Magnitude"))
        self.magnitudeValue.setText(_translate("MainWindow", "TextLabel"))
