# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt5_match.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1269, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saveGoodMatchButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveGoodMatchButton.setGeometry(QtCore.QRect(430, 60, 75, 23))
        self.saveGoodMatchButton.setObjectName("saveGoodMatchButton")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(340, 210, 75, 23))
        self.nextButton.setObjectName("nextButton")
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setGeometry(QtCore.QRect(260, 210, 75, 23))
        self.prevButton.setObjectName("prevButton")
        self.filenameLabel = QtWidgets.QLabel(self.centralwidget)
        self.filenameLabel.setGeometry(QtCore.QRect(60, 50, 281, 20))
        self.filenameLabel.setObjectName("filenameLabel")
        self.templateDateLabel = QtWidgets.QLabel(self.centralwidget)
        self.templateDateLabel.setGeometry(QtCore.QRect(140, 80, 121, 16))
        self.templateDateLabel.setObjectName("templateDateLabel")
        self.matchDateLabel = QtWidgets.QLabel(self.centralwidget)
        self.matchDateLabel.setGeometry(QtCore.QRect(140, 100, 131, 16))
        self.matchDateLabel.setObjectName("matchDateLabel")
        self.saveExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveExitButton.setGeometry(QtCore.QRect(300, 240, 75, 23))
        self.saveExitButton.setObjectName("saveExitButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 80, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 71, 16))
        self.label_2.setObjectName("label_2")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(530, 10, 721, 751))
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setObjectName("image")
        self.saveMaybeMatchButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveMaybeMatchButton.setGeometry(QtCore.QRect(430, 90, 75, 23))
        self.saveMaybeMatchButton.setObjectName("saveMaybeMatchButton")
        self.saveNotGoodMatchButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveNotGoodMatchButton.setGeometry(QtCore.QRect(430, 120, 75, 23))
        self.saveNotGoodMatchButton.setObjectName("saveNotGoodMatchButton")
        self.saveNoMatchButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveNoMatchButton.setGeometry(QtCore.QRect(430, 150, 75, 23))
        self.saveNoMatchButton.setObjectName("saveNoMatchButton")
        self.locationValue = QtWidgets.QLabel(self.centralwidget)
        self.locationValue.setGeometry(QtCore.QRect(140, 120, 181, 16))
        self.locationValue.setObjectName("locationValue")
        self.inCatalogValue = QtWidgets.QLabel(self.centralwidget)
        self.inCatalogValue.setGeometry(QtCore.QRect(290, 80, 111, 16))
        self.inCatalogValue.setFrameShape(QtWidgets.QFrame.Box)
        self.inCatalogValue.setObjectName("inCatalogValue")
        self.mapWidget = QtWidgets.QFrame(self.centralwidget)
        self.mapWidget.setGeometry(QtCore.QRect(30, 320, 471, 441))
        self.mapWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.mapWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mapWidget.setObjectName("mapWidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 61, 16))
        self.label_3.setObjectName("label_3")
        self.magnitudeValue = QtWidgets.QLabel(self.centralwidget)
        self.magnitudeValue.setGeometry(QtCore.QRect(140, 140, 47, 13))
        self.magnitudeValue.setObjectName("magnitudeValue")
        self.regionSelect = QtWidgets.QComboBox(self.centralwidget)
        self.regionSelect.setGeometry(QtCore.QRect(60, 210, 69, 22))
        self.regionSelect.setCurrentText("")
        self.regionSelect.setObjectName("regionSelect")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 190, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 160, 47, 13))
        self.label_5.setObjectName("label_5")
        self.evRegionValue = QtWidgets.QLabel(self.centralwidget)
        self.evRegionValue.setGeometry(QtCore.QRect(140, 160, 47, 13))
        self.evRegionValue.setObjectName("evRegionValue")
        self.messageBox = QtWidgets.QLabel(self.centralwidget)
        self.messageBox.setGeometry(QtCore.QRect(60, 10, 411, 21))
        self.messageBox.setFrameShape(QtWidgets.QFrame.Box)
        self.messageBox.setObjectName("messageBox")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 120, 47, 13))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1269, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveGoodMatchButton.setText(_translate("MainWindow", "Good Match"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.prevButton.setText(_translate("MainWindow", "Prev"))
        self.filenameLabel.setText(_translate("MainWindow", "filename"))
        self.templateDateLabel.setText(_translate("MainWindow", "Template Date"))
        self.matchDateLabel.setText(_translate("MainWindow", "Match Date"))
        self.saveExitButton.setText(_translate("MainWindow", "Save / Exit"))
        self.label.setText(_translate("MainWindow", "Template Time:"))
        self.label_2.setText(_translate("MainWindow", "Match Time:"))
        self.image.setText(_translate("MainWindow", "Match Image goes here"))
        self.saveMaybeMatchButton.setText(_translate("MainWindow", "Maybe Match"))
        self.saveNotGoodMatchButton.setText(_translate("MainWindow", "Not Good"))
        self.saveNoMatchButton.setText(_translate("MainWindow", "No Match"))
        self.locationValue.setText(_translate("MainWindow", "Location"))
        self.inCatalogValue.setText(_translate("MainWindow", "In Catalog"))
        self.label_3.setText(_translate("MainWindow", "Magnitude:"))
        self.magnitudeValue.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "Region Select"))
        self.label_5.setText(_translate("MainWindow", "Ev Region:"))
        self.evRegionValue.setText(_translate("MainWindow", "TextLabel"))
        self.messageBox.setText(_translate("MainWindow", "Message Box"))
        self.label_6.setText(_translate("MainWindow", "Location:"))
